# A sample Gemfile
source "https://rubygems.org"

gemspec
gem 'coveralls', require: false
gem 'devise'
gem 'devise-async'
gem 'machinist_redux'
gem 'rails-controller-testing'
gem "rspec-rails"
gem 'rufus-mnemo'
gem 'simplecov'
gem 'sprockets-rails'


